### ISSUE TITLE
Issue with addition of elements

### ISSUE THREAD

**Issue by avinash-218** [avinash-218/List-ADT#1]
After adding an element to the list by any of the methods, if SLL_ADT::display_List() is called, output is not what is desired

**Comment by Stalin-Raj** [comment]
First remove the destructor in the Node class and make the changes in the display method as like below..
void SLL_ADT::displayList()
{
	Node *temp=first;
	while(temp->next!=NULL)
	{
		cout<<temp->data;
		temp=temp->next;
	}
	cout<<temp->data;
}

**Comment by Stalin-Raj** [comment]
First delete the destructor in the Node class and make the changes below..

void SLL_ADT::displayList()
{
	Node *temp=first;
	while(temp->next!=NULL)
	{
		cout<<temp->data;;
		temp=temp->next;
	}
       cout<<temp->data;
}

**Comment by avinash-218** [comment]
> First delete the destructor in the Node class and make the changes below..
> 
> void SLL_ADT::displayList()
> {
> Node *temp=first;
> while(temp->next!=NULL)
> {
> cout<data;;
> temp=temp->next;
> }
> cout<data;
> }

thanks for remembering Node's destructor

**Comment by avinash-218** [comment]
> First delete the destructor in the Node class and make the changes below..
> 
> void SLL_ADT::displayList()
> {
> Node *temp=first;
> while(temp->next!=NULL)
> {
> cout<data;;
> temp=temp->next;
> }
> cout<data;
> }

**Comment by avinash-218** [comment]
It seems i created node and passes its reference to every methods (instead of creating node pointer and passing
it to the methods as arguements) which is causing the bugs.
This error is because , in the methods i used '->' operator to access instance variables
but i passed only the reference of the object instead of creating node pointer.
